spring.application.name=api
server.port=1010

# Kafka configuration
spring.cloud.zookeeper.connect-string=zookeeper:2181
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Docker compose configuration
spring.docker.compose.enabled=false

# JWT configuration
jwt.secret=${JWT_SECRET:12345678901234567890123456789012}