spring.application.name=db
server.port=2020

# Database configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sozvon}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# Kafka configuration
spring.cloud.zookeeper.connect-string=zookeeper:2181
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Docker compose configuration
spring.docker.compose.enabled=false

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Jackson configuration
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.fail-on-empty-beans=false

