spring.application.name=SLOJHAYA_SHTUKA

jwt_secret = semyon4ik

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
server.port=9091
spring.cloud.zookeeper.connect-string=zookeeper:2181
